### ISSUE TITLE
Zip file doesn't contain the latest merged PR

### ISSUE THREAD

**Issue by rabidscorpio** [awslabs/aws-lambda-ddns-function#10]
This PR (https://github.com/awslabs/aws-lambda-ddns-function/pull/6) is in the ```union.py``` file but not the ```union.py.zip``` file, can you guys update that?

**Comment by jicowan** [comment]
Thanks.  I will upload a new version of the zip tomorrow.

**Comment by jicowan** [comment]
I re-zipped and upload the file.
