### ISSUE TITLE
Unable to import module 'union': No module named union 

### ISSUE THREAD

**Issue by fir3wall** [awslabs/aws-lambda-ddns-function#16]
Hello,

I've just tried to set this up on my company account however after following all of steps my Lambda function errors:
Unable to import module 'union': No module named union

Is that my problem or code problem? Not sure is that correct place to raise it - can raise it with support as got Production service plan.

Thanks
Dariusz

**Comment by jicowan** [comment]
Did you copy and paste the code into a blank Lambda (Python) function or did you upload the zip?

**Comment by fir3wall** [comment]
Hello,
I've copied zip file union.py.zip, I can see following merge request that I've should now do I think union.zip

Thanks
