### ISSUE TITLE
Auto Scaling Group EC2 Instances fail to return tags

### ISSUE THREAD

**Issue by lngarrett** [awslabs/aws-lambda-ddns-function#5]
When an ASG creates instances it propagates the tags at launch. Unlike a manually created instance, these tags are not written to the instance until after the event fires. This introduces a race condition where when the Lambda function pulls tags for the instance none are available. 

I believe a 60 second sleep would resolve this.

**Comment by egalano** [comment]
I am also seeing this issue on regular non auto-scaled instances.

**Comment by jicowan** [comment]
Try adding a line to sleep or increase the sleep time.
