### ISSUE TITLE
Working but showing an error

### ISSUE THREAD

**Issue by gitlab-pano** [awslabs/aws-lambda-ddns-function#7]
The Route53 entries are being created and removed successful, but there are errors in the logs. This happens multiple times per invocation.

`'Item': KeyError Traceback (most recent call last): File "/var/task/lambda_function.py", line 80, in lambda_handler instance = instance['Item']['InstanceAttributes'] KeyError: 'Item'`

```
'Item': KeyError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 80, in lambda_handler
instance = instance['Item']['InstanceAttributes']
KeyError: 'Item'
```

**Comment by jicowan** [comment]
You may be getting an error because the record for the instances does not exist in the DDB table.  The function should not retrieve the instance attributes from the table unless you're terminating or stopping it. It's as if the else statement is being ignored.

**Comment by rbmandadapu** [comment]
'detail': KeyError
Traceback (most recent call last):
File "/var/task/Cloudtraillambdamonitor.py", line 40, in lambda_handler
eventname = event['detail']['eventName']
KeyError: 'detail'



Someone help me with this, I got this error while running Lambda function to monitor CloudTrail evnets.

**Comment by jicowan** [comment]
Did you configure the CloudWatch Event?  Which EC2 events are you listening for?

________________________________

**Comment by rbmandadapu** [comment]
Yes, I did, I'm using this service to monitor Cloud Trail events.

**Comment by jicowan** [comment]
The error you getting indicates that the json payload does not have a 'detail' node.  What events are you sending to the function?

________________________________

**Comment by rbmandadapu** [comment]
Below are the events that I want to track,

“StopLogging”
“StartLogging”
“UpdateTrail”
“DeleteTrail”
“CreateTrail”
“RemoveTags”
“AddTags”

When I use CF to run, I got the error that I mentioned, But When I configure it manually I'm getting error in Lambda console like this " Unable to import module 'lambda_function': No module named lambda_function' "

**Comment by rbmandadapu** [comment]
Got it. I was checking, I found this repo. It looks like a similar issue. anyway, thanks though. Could you please post me the correct repo. That would be helpful.

**Comment by jicowan** [comment]
What repo were you looking for?  What repo did you pull from Github?

________________________________

**Comment by rbmandadapu** [comment]
I was looking for Lambda and CloudTrail Repo, But I didn;t find anything helpful here, everyone is saying that it is a wrong repo. I guess I can take this issue to Amazon Support.

**Comment by jicowan** [comment]
Have you tried posting a comment on the blog post yet?
